### PR TITLE
First Pass

### PR DESCRIPTION
**Pull request by baberabb**
Did a first pass of both the repos and to see how much work is required. The NYPL folks have done a great job though and the data seems to be pretty comprehensive IMO. Most of my time was spent trying to coerce the datasets into the required format. 

The registration repo consists of xml files parsed from each volume of the Copyright Catalog. Here they took a maximalist approach incorporating as much data as possible for each entry; but for our purposes, the relevant columns are the registration date (`regDate`) _and_ the registration number (`regnum`). These can be matched in the much leaner dataset (tab delimited files for each volume) of the renewal entries. We need both as the registration numbers are not unique as they restarted the sequence sometime in the 1950's.  I have uploaded the consolidated renewal dataset [here](https://huggingface.co/datasets/baber/cce-renewals). Still cleaning up the registration data. There us _a lot_ of data in nested hierarchies and just thinking about how much to prune. 

I have added a notebook for with some summary statistics as well as a sample of the registration data (`sample.csv`).  Also added the simple xml parsing script i used. 

After removing entries with registration dates  > 1963 and  filtering out foreign entries (`regnum` starting with AF == `93,793`) , and removing some duplicates, there are about 443,333 entries remaining. Did not include entries (~ 200,000) without a number or date.  This might just be a parsing error on my part as the data can be duplicated in another attribute I missed. Also need to generally verify the parsing logic so will take another look.

@StellaAthena

### CODE REVIEW

**Comment by StellaAthena** [comment]
> I have uploaded the consolidated renewal dataset [here](https://github.com/EleutherAI/pd-books/pull/baber/cce-renewals).

The link to the "consolidated renewal dataset" is 404'ing for me.

> After removing entries with registration dates > 1963

I think you mean "<"?

> filtering out foreign entries (regnum starting with AF == 93,793)

Can you elaborate on this? What is this field, why does it starting with `AF == 93,793` mean it's foreign?

> there are about 443,333 entries remaining.

What is this the number of entries of? Renewals? Registrations - Renewals?

> Did not include entries (~ 200,000) without a number or date. This might just be a parsing error on my part as the data can be duplicated in another attribute I missed.

Could also be an OCR error or a processing error before we got the data... have you checked if every entry (before you did anything to it) had values?

**Comment by baberabb** [comment]
> The link to the "consolidated renewal dataset" is 404'ing for me.

Sorry about this. The correct link is [here](https://huggingface.co/datasets/baber/cce-renewals). I will also update the OP. The columns we match are original registration date (`odat`) and original registration number (`oreg`).

> I think you mean "<"

After _removing_ entries with registration dates > 1963. But I actually had used >= 1963 ([wrongly](https://www.copyright.gov/circs/circ15.pdf) it [turns](https://en.wikipedia.org/wiki/Copyright_renewal_in_the_United_States) out!): only works registered on or after 1 January 1964 are excluded from requiring a renewal.

> Can you elaborate on this? What is this field, why does it starting with AF == 93,793 mean it's foreign?

Registration numbers follow the [class][serial number] format and foreign works were provided a separate numbering system `A—Foreign` (standardised to AF). Their [repo](https://github.com/NYPL/catalog_of_copyright_entries_project/blob/master/guide.md) provides this handy table for the sub-categories (interim etc.):

| `<regNum>`| regularized (for `regnum` attribute)|
|-------------|-------------------------------------|
| A 963122| A963122 |
| A—Foreign 32851 | AF32851 |
| A for. 48359 | AF48359 |
| A ad int. 8956 | AI8956 |
| A int. 241 | AI241 |

Though looking at it again, looks like the AF numbering is duplicated (2nd and 3rd row). Also have noticed some rows have a "originally published abroad" note, but are given an `A` format. Need to verify how extensive this is.

> What is this the number of entries of? Renewals? Registrations - Renewals?

443,333 -> This is a very (very) rough estimate of the registrations remaining in our dataset (after filtering out > 1963, valid and dedeuplicated regdate && regnum) which did not have a match in the renewal dataset, aka what we can use. However (see below)

> have you checked if every entry (before you did anything to it) had values?

Umm. I haven't but I should have though lol. My main pipeline was (below from the notebook):

Total entries in dataset: 2,169,792 (not all unique as a part of a book can have its own row)
After filtering for regdate < 1963: 834,182
After removal of N/A regdate _or_ regnum: 672,125
After filtering for renewal matches: 537,126
After removing `AF` class: 443,333

Have also realised I overlooked the distinction between `regNum` and `regnum`. The `regNum` is a verbatim transcription, while `regnum` is standardised for the XML (as in the table above). More importantly they tried to tried to ensure that every entry _should_ have a `regNum` (around ~20,000 without in the original dataset of 2m), while the other one has much more missing data.  I'll try to give you an update in a couple of days with these errors fixed.

Just to recap:
- [ ] Include 1963 registration dates.
- [ ] Verify foreign entries and esp. cross reference A-foreign.
- [ ] Use and cross-reference `regNum`.

**Comment by StellaAthena** [comment]
Thanks for the thorough reporting! I'm surprised by the foreign labels, as the NYPL guy I was talking to was making it sound like that was going to be a meaningfully difficult task.

A couple final questions:
1. How many entries (in each dataset) lack a value for `regdate && regnum`? This seems like a good proxy for the number of entries that we need to go back and redo the ORC for.
2. How many renewals are there that we cannot match to registrations? Since every renewal should match a registration, this is a good way to gauge how much we might be missing (and exploratory analysis could reveal why we are missing them)

**Comment by StellaAthena** [comment]
Thanks for the thorough reporting! I'm surprised by the foreign labels, as the NYPL guy I was talking to was making it sound like that was going to be a meaningfully difficult task.

A couple final questions:
1. How many entries (in each dataset) lack a value for `regdate && regnum`? This seems like a good proxy for the number of entries that we need to go back and redo the ORC for.
2. How many renewals are there that we cannot match to registrations? Since every renewal should match a registration, this is a good way to gauge how much we might be missing (and exploratory analysis could reveal why we are missing them)

**Comment by StellaAthena** [comment]
Thanks for the thorough reporting! I'm surprised by the foreign labels, as the NYPL guy I was talking to was making it sound like that was going to be a meaningfully difficult task.

A couple final questions:
1. How many entries (in each dataset) lack a value for `regdate && regnum`? This seems like a good proxy for the number of entries that we need to go back and redo the ORC for.
2. How many renewals are there that we cannot match to registrations? Since every renewal should match a registration, this is a good way to gauge how much we might be missing (and exploratory analysis could reveal why we are missing them)

**Pull request merged**
